import { use } from "react";
import { useLanguage } from "./useLanguage";

// One JSON chunk per locale, generated by scripts/fetch-content.mjs; loaded once, then cached
const loaders = import.meta.glob("../content/*.json", { import: "default" });
const cache = new Map();

const load = (lang) => {
  if (!cache.has(lang)) {
    cache.set(lang, (loaders[`../content/${lang}.json`] ?? loaders["../content/en.json"])());
  }
  return cache.get(lang);
};

export const useContent = () => use(load(useLanguage().currentLanguage));
